# Generated by Django 5.0.4 on 2024-05-01 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(default=django.utils.timezone.now)),
                ('raison', models.TextField()),
                ('etat_hydrodynamique', models.CharField(max_length=500)),
                ('etat_respiratoire', models.CharField(max_length=500)),
                ('echographie', models.CharField(max_length=500)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tension', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fievre', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Malade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('femme', 'Femme'), ('homme', 'Homme')], max_length=20)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(default=django.utils.timezone.now)),
                ('contenue', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecine.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(default=django.utils.timezone.now)),
                ('raison', models.TextField()),
                ('malade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medecine.malade')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendezvous',
            field=models.OneToOneField(limit_choices_to={'consultation__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='medecine.rendezvous'),
        ),
    ]
